----------------- ACESSANDO O BANCO
--   mysql -h localhost -u root -p 
----------------- VERIFICANDO OS BANCOS EXISTENTES
SHOW DATABASES;

----------------- CRIANDO UM BANCO
CREATE DATABASE NOME_BANCO;

----------------- USAR DETERMINADO BANCO
USE NOME_DATABASE;

----------------- VISUALIZAR TABELAS NESSE BANCO
SHOW TABLES;

----------------- CRIANDO UMA TABELA SIMPLES
CREATE TABLE NOME_TABLE(
  nome VARCHAR(30) NOT NULL,
  email VARCHAR(50) NOT NULL,
  idade INT NOT NULL
);

----------------- MOSTRA A DESCRIÇÃO DA TABELA
DESC NOME_TABELA;

----------------- MOSTRA COMO FOI CRIADO AQUELA TABELA
SHOW CREATE TABLE NOME_TABELA;

----------------- INSERI DADOS NO BANCO
INSERT INTO NOME_TABELA(nome, email, idade)
VALUES ("Andre","andre@email.com",31);

----------------- SELECIONANDO DADOS
SELECT * FROM NOME_TABELA;

----------------- USANDO O WHERE
SELECT * FROM NOME_TABELA WHERE IDADE >= 18;

----------------- DELETAR REGISTROS
DELETE FROM NOME_TABELA WHERE ID = 2;

----------------- ATUALIZADO CAMPO DA TABELA
UPDATE NOME_TABELA SET nome = 'novo nome' WHERE nome = 'NOME ANTIGO';